# project day 1 (2018 - 01 - 17)

<p><a href = "./index.html">back to main page</a></p>

## 주제선정 - 교환학생용 지도

### 순서 예상

1. 교환학생 문서 가져오기
2. 학교이름으로 구글 지도에 위치를 표시하기
3. 지도선택또는 학교이름 검색으로 수기를 모두 볼 수 있게 => 추후 다른 학교자료도 포함한다.
(학교는 현재 지원할 수 있는 학교가 아니라, 수기가 있는 학교로 한다)

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

## 파이썬 복습 - NUMPY

파이썬의 리스트는 느리다. append를 통해서 쉽게 길이를 바꿀수 있지만, 공간이 더 필요한 경우 메모리에 새로운 공간을 만들어서 모든 값들을 이동시켜야한다(overhead 무지 큼) - https://smlee729.github.io/python/data%20structure/2015/03/02/1-list-allocation.html 참고
=> numpy는 이름 보완하여 적은 메모리로 데이터를 빠르게 처리할 수 있다! 

* (numpy == 배열로 생각) 
* 주의 1: 리스트와는 다르게 모든 원소가 같은 자료형이어야함! 
* 주의 2: 원소의 개수를 바꿀수 없음! 

In [2]:
import numpy as np #numpy패키지 임포트

In [4]:
#1차원 어레이
ar1 = np.array([0,1,2,3,4])
ar1

array([0, 1, 2, 3, 4])

In [6]:
type(ar1) #numpy어레이의 타입은 ndarray이다

numpy.ndarray

In [8]:
#벡터화 연산
data = [0,1,2,3,4]

In [9]:
#data의 각각의 값을 두배를 시키기 위해 포문을 이용하지 않고, numpy를 이용할 수 있다

n_data = np.array(data)
n_data

array([0, 1, 2, 3, 4])

In [12]:
2 * n_data #벡터화 연산을 사용하는 것이 속도가 더 빠르다

array([0, 2, 4, 6, 8])

In [13]:
 #리스트에 2배한 것과 numpy배열에 2배한 것 결과 차이
print("리스트 2배: ", data*2) #길이가 두배가됨
print("numpy 배열 2배: ", n_data*2) #각각의 값이 연산이 된다

리스트 2배:  [0, 1, 2, 3, 4, 0, 1, 2, 3, 4]
numpy 배열 2배:  [0 2 4 6 8]


### 1. 2차원 3차원도 비슷하게 적용된다. 다만 차원의 개념은 선형대수학 공부를 통해서
### 2. 상세하게 익히는 것이 더욱 도움이 된다.(패키지 사용을 통한 이해는 한계가 느껴진다.)
### 3. 알아야 하는 몇가지 기교들 리스트을 아래에

In [14]:
#배열의 길이는 len으로
#1차원
a = np.array([0,1,2,3])
len(a)

4

In [16]:
#2차원
b = np.array([[0,1,2,3],[4,5,6,7]])
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [17]:
print("b의 행길이 ",len(b))
print("b의 열길이 ",len(b[0]))

b의 행길이  2
b의 열길이  4


In [21]:
b.shape #행열구할수있음

(2, 4)

In [23]:
#3차원
c = np.array([[[0,1],[2,3]],[[0,1],[2,3]]])
c

array([[[0, 1],
        [2, 3]],

       [[0, 1],
        [2, 3]]])

In [24]:
c.shape

(2, 2, 2)

In [25]:
# 3차원 배열의 슬라이싱

d = np.array([[[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]],
              
              [[11,12,13,14],
               [15,16,17,18],
               [19,20,21,22]]]) 
# 2*3*4 array = > 2개의 3행 4열로 생각

In [28]:
#3차원의 행 열 깊이
len(d), len(d[0]), len(d[0,0])

(2, 3, 4)

In [27]:
# ndim은 차원, shape은 크기를 반환
print(d.ndim)
print(d.shape)

3
(2, 3, 4)


In [29]:
# [] 안에 ,로 접근하기
# 슬라이싱은 :로 

In [31]:
# 배열 인덱식 ! = 배열의 위치정보를 받아오는 것!!

# 1. 불리언 배열 인덱싱

a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True, False, True, False, True, False])
a[idx] #idx가 true인 값만 출력

array([0, 2, 4, 6, 8])

In [34]:
a % 2 == 0 #짝수인지 인덱스를 받아온다

array([ True, False,  True, False,  True, False,  True, False,  True, False], dtype=bool)

In [35]:
a[a%2==0] #짝수만 출력

array([0, 2, 4, 6, 8])

In [37]:
# 2. 정수 배열 인덱싱
b = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8]) #이 인덱스 각각이 배열의 원소를 가리키는 정수여야함
b[idx]

array([11, 33, 55, 77, 99])

In [38]:
# 다차원에서도 가능
c = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
c[:,[True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [40]:
c[:,[1,1,1]]

array([[ 2,  2,  2],
       [ 6,  6,  6],
       [10, 10, 10]])

In [41]:
c[[2,0,1],:]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [44]:
d = np.array([[[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]],
              
              [[11,12,13,14],
               [15,16,17,18],
               [19,20,21,22]]])
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [45]:
d[:,0:2,[1,1,1]]

array([[[ 2,  2,  2],
        [ 6,  6,  6]],

       [[12, 12, 12],
        [16, 16, 16]]])

#### numpy 기본 복습 끝(2018/01/17)